trigger:
- master

pool:
 vmImage: 'ubuntu-16.04'

stages:
  - stage: Build_Stage
    displayName: Build Nuget Packages
    jobs:
      - job: BuildNuget
        displayName: Build nuget packages
        variables: 
            BuildConfiguration: 'release'
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'restore'
              projects: '**/*.csproj'
              feedsToUse: 'select'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              projects: '**/*.csproj'
              arguments: '--configuration $(BuildConfiguration)'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'pack'
              packagesToPack: '**/*.csproj'
              versioningScheme: 'off'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
              nuGetFeedType: 'internal'
              publishVstsFeed: 'cc27578c-cb08-4001-8233-a80286851f5b/8d9eeaef-9d61-43eb-8bc3-bc833378259e'